### PR TITLE
The DaneBook, premier social interfacing and mobi-social kinetics.

### PR DESCRIPTION
**Pull request by behaviary**
Using peer first technologies, we've created a platform that interfaces with dane-centric integration. This is an unprecedented social network.

### CODE REVIEW

**Comment by betweenparentheses** [comment]
Hey dude, you might want your README to give credit to yourself instead of ... me.  You did a lot of work!

**Comment by behaviary** [comment]
Um I think I'm a bit slow today, can you comment on the line? I couldn't find what thou speakest of

**Comment by betweenparentheses** [comment]
Oh, I'm an idiot. I was looking at your fork of my repo. HA.

On Mon, Oct 27, 2014 at 3:07 PM, Peter notifications@github.com wrote:

> Um I think I'm a bit slow today, can you comment on the line? I couldn't
> find what thou speakest of
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vikingeducation/danebook/pull/5#issuecomment-60678097
> .

## 

_Michael Alexander_

(310) 429-8822

alexandermw@gmail.com

**Comment by behaviary** [comment]
I'm having a moment as well. I accidentally forked your repo when I went to comment on the SSH file ha ha.

**Pull request closed without merging**
